- name: Instala o Puppet Server
  apt:
    name: puppetserver
    state: present
    update_cache: yes
    when: ansible_os_family == 'Ubuntu'

- name: Inicia o Puppetserver
  service:
    name: puppetserver
    state: started
    enabled: yes
