---
- name: Playbook de Teste
  hosts: all
  tasks: 
    - name: Remove o Apache2 nas maquinas Ubuntu
      apt: 
        name: apache2
        state: absent
      when: ansible_os_family == 'Debian'

    - name: Remove o Apache2 nas maquinas CentOS
      yum:
        name: httpd
        state: absent
      when: ansible_os_family == 'RedHat'


    - name: Instala o nginx
      package:
        name: nginx
        state: present 
